{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_demo1.TestClass object at 0x000001705A846390>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_demo1.py:10: AssertionError"}, "start": 1571039646080, "stop": 1571039646080, "uuid": "6ffb7709-248a-4dbc-9750-fd25a9172e47", "historyId": "4b2a7fa4666a521c61a69e475448b55a", "fullName": "ptest+allure.test_demo1.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "ptest+allure"}, {"name": "suite", "value": "test_demo1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DT003-SZ01-NEWT"}, {"name": "thread", "value": "1324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ptest+allure.test_demo1"}]}